# Generated by Django 4.2 on 2023-04-06 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("fill_method", models.CharField(max_length=20, null=True)),
                ("time_of_week", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelCandleHourly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("time_of_year", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=10)),
                ("description", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ModelExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=100)),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddConstraint(
            model_name="modelexchange",
            constraint=models.UniqueConstraint(
                fields=("value",), name="unique_exchange_value"
            ),
        ),
        migrations.AddField(
            model_name="modelcurrency",
            name="exchange",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="okx_app.modelexchange",
            ),
        ),
        migrations.AddField(
            model_name="modelcandlehourly",
            name="base_ccy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)sbase_ccy",
                to="okx_app.modelcurrency",
            ),
        ),
        migrations.AddField(
            model_name="modelcandlehourly",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="okx_app.modelexchange"
            ),
        ),
        migrations.AddField(
            model_name="modelcandlehourly",
            name="quote_ccy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)squote_ccy",
                to="okx_app.modelcurrency",
            ),
        ),
        migrations.AddField(
            model_name="modelcandle",
            name="base_ccy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_ccy",
                to="okx_app.modelcurrency",
            ),
        ),
        migrations.AddField(
            model_name="modelcandle",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="okx_app.modelexchange"
            ),
        ),
        migrations.AddField(
            model_name="modelcandle",
            name="quote_ccy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quote_ccy",
                to="okx_app.modelcurrency",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcurrency",
            constraint=models.UniqueConstraint(
                fields=("value",), name="unique_currency_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcandlehourly",
            constraint=models.UniqueConstraint(
                fields=("exchange", "base_ccy", "quote_ccy", "time_of_year"),
                name="modelcandlehourlyunique_candle",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcandle",
            constraint=models.UniqueConstraint(
                fields=("exchange", "base_ccy", "quote_ccy", "time_of_week"),
                name="unique_candle",
            ),
        ),
    ]
